---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-qwen3-06b
  namespace: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: model-import-job-ollama-qwen3-06b
  namespace: ollama
spec:
  template:
    spec:
      containers:
      - name: model-importer
        image: ghcr.io/terrywu510/model:ollama-qwen3-06b
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /model-cache/model &&
          cp -r /model/* /model-cache/model
        volumeMounts:
        - name: model-storage
          mountPath: /model-cache
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: ollama-qwen3-06b
      restartPolicy: Never