---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  #storageClassName: kubernetes-csi-rbd-sc
  storageClassName: ceph-ext4